### ISSUE TITLE
用词法分析来做计算器是大材小用了

### ISSUE THREAD

**Issue by 15951836388** [dengsgo/math-engine#1]
作者博客也说了，词法用来做脚本解析正好的。

计算器的比较合适实现方式，是逆波兰式（后缀表达式）

**Comment by dengsgo** [comment]
是的，单纯做计算器的话后缀表达式是个很直接的实现算法。  
这里采用抽象语法树的方式，主要是为了以后的扩展性，比如未来增加三角函数的支持 `1+sin(90)+cos(0)`，那我就可以很自然在之前词法和语法分析基础上，来做这个函数支持。

**Comment by 15951836388** [comment]
恩恩，语法树的扩展肯定更强。
打算加个ui库来做计算器吗？

**Comment by dengsgo** [comment]
> 恩恩，语法树的扩展肯定更强。
> 打算加个ui库来做计算器吗？

这个 repo 目的是做表达式计算的库，供第三方调用。不会增加 ui 支持。

**Comment by 15951836388** [comment]
好的，我来用。
支持负数吗?

**Comment by dengsgo** [comment]
你可以[下载已经编译好的 demo 文件](https://github.com/dengsgo/math-engine/releases)，运行，输入一些数学表达式，来确认这个库是否符合自己的要求。

**Comment by 15951836388** [comment]
![image](https://user-images.githubusercontent.com/14047483/60854195-de688600-a231-11e9-9a15-ac465847fb25.png)
不支持负数

**Comment by dengsgo** [comment]
> ![image](https://user-images.githubusercontent.com/14047483/60854195-de688600-a231-11e9-9a15-ac465847fb25.png)
> 不支持负数

这是一个 **bug** ，需要针对性的修复一下。稍晚一些时间会修复这个问题，感谢发现问题。

**Comment by dengsgo** [comment]
> ![image](https://user-images.githubusercontent.com/14047483/60854195-de688600-a231-11e9-9a15-ac465847fb25.png)
> 不支持负数

问题已修复，可以重新[下载 demo](https://github.com/dengsgo/math-engine/releases) 运行试下。

**Comment by 15951836388** [comment]
![image](https://user-images.githubusercontent.com/14047483/60859122-dd405480-a243-11e9-9701-b91ad6ea4e64.png)
负号和括号并用的情况bug

**Comment by dengsgo** [comment]
> ![image](https://user-images.githubusercontent.com/14047483/60859122-dd405480-a243-11e9-9701-b91ad6ea4e64.png)
> 负号和括号并用的情况bug

感谢贡献测试用例，当前已修复。[最新 demo](https://github.com/dengsgo/math-engine/releases)

**Comment by 15951836388** [comment]
暂时没发现问题
