### ISSUE TITLE
希望可以增加表达式功能

### ISSUE THREAD

**Issue by 15951836388** [dengsgo/math-engine#10]
比如可以判断 double(1,2)<1  double是自定义函数

应用场景主要是，策划可以配置一些条件，

比如：get战斗力(uid)>=10w  get战斗力(uid)是自定义函数

可以参考 https://github.com/Knetic/govaluate

**Comment by dengsgo** [comment]
这个是逻辑表达式了，已经超过了数学计算的范畴，功能增加待评估。

`double(1,2)<1 ` 这种表达式是在可以在 math-engine 里面实现的。你可以注册一个自定义的函数，比如 `compare(x, y)`，实现你的比较逻辑，之后表达式输入就可以为 `compare( double(1,2), 1 )`，从而实现你的业务。

**Comment by 15951836388** [comment]
好的，那开发一下toStr的权限
type ExprAST interface {
	toStr() string
}
这样就可以 compare(x, >,y),函数的内容可以更加灵活

**Comment by 15951836388** [comment]
目前是只能传数字参数的。不能实现
![image](https://user-images.githubusercontent.com/14047483/97655756-c6f58200-1aa0-11eb-96cb-ba6b265603c6.png)

**Comment by dengsgo** [comment]
`>` 不是有效字符,识别不了。

建议分别创建相应自定义函数，比如大于比较`gte(x, y)`，小于比较 `lte(x, y)`，相等比较 `eq(x, y)` 来使用。
