### ISSUE TITLE
建议TrigonometricMode的设置取消，而通过优化表达式来解决

### ISSUE THREAD

**Issue by smally84** [dengsgo/math-engine#11]
否则，一般情况下，本通过表达式可以解决的事情，结果又需要引入代码来解决，违背初衷

**Comment by dengsgo** [comment]
TrigonometricMode 是全局有效的，一般建议是在自己的代码 `init()` 函数或者其他初始化程序的函数方法中就设置好它，这样在任意调用引擎计算时都会按统一设置约定的模式计算而不会出现歧义。不建议在调用引擎计算的前后去调整它，这样可能会导致上下文不一致，引起混乱。

如果想避免该变量带来的副作用，建议通过自定义函数来增加相关自己的处理函数，不使用内置的三角系列函数。
