### ISSUE TITLE
建议 使用注册接口的方式 来 实现 自定义函数

### ISSUE THREAD

**Issue by 15951836388** [dengsgo/math-engine#12]
由用户自己实现接口类

这样有更好的灵活性和扩展性

**Comment by dengsgo** [comment]
目前的 `regFunction` 方法应该是可以满足大部分需求的，但使用接口注册也是个好主意。

可以提供下目前 `regFunction` 不能满足你的哪些需求吗

**Comment by 15951836388** [comment]
注册 函数 局限性过强，而且不能传递额外一些对象，只能做简单运算，根本做不了复杂功能。

需求，之前的人也提过，注册的函数，要获取一些对象的值来参与计算，光函数是不行的

**Comment by dengsgo** [comment]
这个项目目前更多的还是专注数学表达式部分，如果超出数值计算这部分的话，可能不会有相应实现来支持.

**Comment by 15951836388** [comment]
用接口，本来就满足了数学计算功能。至于用户如何拓展，为何要限制呢？

**Comment by 15951836388** [comment]
接口也是，go推荐的方式

**Comment by dengsgo** [comment]
> 用接口，本来就满足了数学计算功能。至于用户如何拓展，为何要限制呢？

视场景而定，并不是要做限制。你可以贴一下你需要的调用方法伪代码（比如如何用接口注册，注册方法传值 等等），我评估后再来进一步讨论。

**Comment by 15951836388** [comment]
type ICustomFunction interface {
	Name() string
	Cal() float32
	Clear()
	SetArgsOther(argsOther ...interface{})
}

type CustomFunction struct {
	//各种自定义的额外数据
	argsOther []interface{}
}

//设置一些其他参数
func (t *CustomFunction) SetArgsOther(argsOther ...interface{}) {
	t.argsOther = argsOther
}

//清理，防止多次计算污染
func (t *CustomFunction) Clear() {
	t.argsOther = nil
}

//函数名
func (t *CustomFunction) Name() string {
	return "CustomFunction"
}

//计算实现
func (t *CustomFunction) Cal(args ...interface{}) float32 {
	a := args[0].(int32)
	b := args[1].(int32)
	c := t.argsOther[0].(*User)
	return float32(a + b + c.C)
}

type User struct {
	C int32
}

func main() {
	//用接口类型注册
	//engine.Register(&CustomFunction{})

	//用户使用时的封装

	//获取已经注册的方法
	ifun := engine.GetFun("CustomFunction")
	//设置额外参数
	user := User{C: 10}
	ifun.SetArgsOther(user)
	//计算（engine内部调用Cal接口）
	engine.ParseAndExec(`CustomFunction(1,2)+ 3`)
	//清理
	ifun.Clear()
}

**Comment by 15951836388** [comment]
非注册版

//engine 内部使用
type ICustomBase interface {
	Name() string
	Cal() float32
}

//用户实现
type CustomFunction struct {
	//各种自定义的额外数据
	argsOther []interface{}
}

//设置一些其他参数
func (t *CustomFunction) SetArgsOther(argsOther ...interface{}) {
	t.argsOther = argsOther
}

//函数名
func (t *CustomFunction) Name() string {
	return "CustomFunction"
}

//计算实现
func (t *CustomFunction) Cal(args ...interface{}) float32 {
	a := args[0].(int32)
	b := args[1].(int32)
	c := t.argsOther[0].(*User)
	return float32(a + b + c.C)
}

type User struct {
	C int32
}

func main() {

	//非注册，直接传入接口版，推荐
	ifun := &CustomFunction{}
	//设置额外参数
	user := User{C: 10}
	ifun.SetArgsOther(user)
	//计算（engine内部调用ifun的Cal接口）
	engine.ParseAndExec2(ifun, `CustomFunction(1,2)+ 3`)
}

**Comment by 15951836388** [comment]
算了，还是专注数学表达式把
