### ISSUE TITLE
请问下有没有计划实现比较运算符

### ISSUE THREAD

**Issue by jackvicp** [dengsgo/math-engine#13]
请问下有没有计划实现比较运算符， 如: ==, !=, > , <,>=, <=

**Comment by dengsgo** [comment]
> 请问下有没有计划实现比较运算符， 如: ==, !=, > , <,>=, <=

此类运算符属于逻辑运算符，`math-engine` 目前只针对算术运算提供支持，暂无此类实现计划。

您也可以通过注册自定义函数来实现此类需求。如：注册 `equal`函数, 在表达式中使用 equal(x, y) 来获得结果。

**Comment by jackvicp** [comment]
好的。谢谢！
















在 2021-11-18 13:58:59，"Deng.Liu" ***@***.***> 写道：

请问下有没有计划实现比较运算符， 如: ==, !=, > , <,>=, <=

此类运算符属于逻辑运算符，math-engine 目前只针对算术运算提供支持，暂无此类实现计划。

您也可以通过注册自定义函数来实现此类需求。如：注册 equal函数, 在表达式中使用 equal(x, y) 来获得结果。

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
