### ISSUE TITLE
公式中的非法内容如何自动清除？

### ISSUE THREAD

**Issue by ncerp** [dengsgo/math-engine#18]
不知道是否已经提供了这种功能，我的公式，里面会含有一些不可解析的字符，比如
100*100米/扎=10000
这是我希望的结果，这里的 米/扎 显然是无法解析的。
这只是个例子，可能还会有 100kg/桶 等等诸如此类的。
有没有这样的功能，就是可以把这种无法运算的内容自动清除掉？

**Comment by dengsgo** [comment]
> 不知道是否已经提供了这种功能，我的公式，里面会含有一些不可解析的字符，比如 100*100米/扎=10000 这是我希望的结果，这里的 米/扎 显然是无法解析的。 这只是个例子，可能还会有 100kg/桶 等等诸如此类的。 有没有这样的功能，就是可以把这种无法运算的内容自动清除掉？

`100*100米/扎` 对于 `engine`来说是非法算式，在预处理阶段就会报错 `symbol error`，也没有清除的逻辑处理。

业务上如果需要清除，可以考虑使用正则或者 unicode 范围判断去处理。

**Comment by ncerp** [comment]
明白，多谢多谢。如果有个这么样的方法调用一下就清掉非法可能就更棒了。多谢了，我是用的自己清除的，但感觉不好写，把公式的支持都搞没了，我这样干的：

`	reg := regexp.MustCompile("[/][\u2e80-\ua4cf]|[/][\uf900-\ufaff]|[/][\ufe30-\ufe4f]")
	vfomula = reg.ReplaceAllString(vfomula, "")
	reg = regexp.MustCompile("[\u2e80-\ua4cf]|[\uf900-\ufaff]|[\ufe30-\ufe4f]")
	vfomula = reg.ReplaceAllString(vfomula, "")
	reg = regexp.MustCompile("[A-Z]")
	vfomula = reg.ReplaceAllString(vfomula, "")
	reg = regexp.MustCompile("[a-z]")
	vfomula = reg.ReplaceAllString(vfomula, "")
	reg = regexp.MustCompile("[/][A-Z]")
	vfomula = reg.ReplaceAllString(vfomula, "")
	reg = regexp.MustCompile("[/][a-z]")
	vfomula = reg.ReplaceAllString(vfomula, "")
	reg = regexp.MustCompile("[^.+*-/()0-9]+")
	vfomula = reg.ReplaceAllString(vfomula, "")
`
go也不是太精，东拼西凑能干了。就是把公式都清的不支持了
