### ISSUE TITLE
bug： "2_5*2" 结果是50

### ISSUE THREAD

**Issue by 15951836388** [dengsgo/math-engine#2]
输入有异常符号

	Tok:  strings.ReplaceAll(p.Source[start:p.offset], "_", ""),

代码直接替换了 "_"，应该报错，或者返回0

**Comment by dengsgo** [comment]
数字中出现`_`是合法的，用于数字分割。通常会在数字较长时加入`_`来提高可读性。README中有说明。  
  

![image](https://user-images.githubusercontent.com/7929002/63987796-0b3b6a00-cb0c-11e9-9c4b-241a89cf9838.png)
