### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by button-chen** [dengsgo/math-engine#21]
计算这个会得到错误的结果： 
(((3 / 3 - 3 - 3) / (3 * 3) / 3 / 3) - ((3 / 3) * (3 / 3) - ((3 * 3) * (3 * 3))) / ((3 / 3) * (3 / 3) - 3 * 3 / (3 / 3) * ((3 / 3) / 3 / 3 + 3 - 3 * (3 / 3))))                                  

正确结果应该是：-1.8014398509481984e+17
math-engine结果： 7.272877265274083e+16

**Comment by button-chen** [comment]
可以使用python验证：
![Uploading calc1.png…]()

**Comment by button-chen** [comment]
可以使用python验证正确结果

**Comment by Jarcis-cy** [comment]
这个算式的结果应该是无意义的，因为拆分一下就是：
`((3 / 3 - 3 - 3) / (3 * 3) / 3 / 3)` - `((3 / 3) * (3 / 3) - ((3 * 3) * (3 * 3)))` / `((3 / 3) * (3 / 3) - 3 * 3 / (3 / 3) * ((3 / 3) / 3 / 3 + 3 - 3 * (3 / 3)))`
而`((3 / 3) * (3 / 3) - 3 * 3 / (3 / 3) * ((3 / 3) / 3 / 3 + 3 - 3 * (3 / 3)))`的结果可以化为：

![image](https://github.com/dengsgo/math-engine/assets/39492464/32093e40-fa78-401a-901c-4b0b485220ff)


这个的结果手工计算或者使用wolframalpha就可以知道，是0，任何数除0都没有意义

整体算式计算地址：[wolframalpha](https://www6b3.wolframalpha.com/input?i=%28%28%283+%2F+3+-+3+-+3%29+%2F+%283+*+3%29+%2F+3+%2F+3%29+-+%28%283+%2F+3%29+*+%283+%2F+3%29+-+%28%283+*+3%29+*+%283+*+3%29%29%29+%2F+%28%283+%2F+3%29+*+%283+%2F+3%29+-+3+*+3+%2F+%283+%2F+3%29+*+%28%283+%2F+3%29+%2F+3+%2F+3+%2B+3+-+3+*+%283+%2F+3%29%29%29%29&lang=en)
分母计算地址：[wolframalpha](https://www6b3.wolframalpha.com/input?i=%283+%2F+3%29+*+%283+%2F+3%29+-+3+*+3+%2F+%283+%2F+3%29+*+%28%283+%2F+3%29+%2F+3+%2F+3+%2B+3+-+3+*+%283+%2F+3%29%29&lang=en)

**Comment by dengsgo** [comment]
> 这个算式的结果应该是无意义的...

如同楼上所述，算式本身会出现除以0，计算结果是无意义的。可以通过 mathsolver 可视化：

<img width="591" alt="image" src="https://github.com/user-attachments/assets/426bae91-d6da-4ce1-981f-0c91bb63929b">

算式链接：[Math Solver](https://mathsolver.microsoft.com/en/solve-problem/%60frac%7B%60frac%7B%60frac%7B%60frac%7B%60frac%7B3%7D%7B3%7D-3-3%7D%7B3%60cdot3%7D%7D%7B3%7D%7D%7B3%7D-%60frac%7B3%7D%7B3%7D%60frac%7B3%7D%7B3%7D-((3%60cdot3)*(3%60cdot3)%7D%7B%60frac%7B3%7D%7B3%7D%60frac%7B3%7D%7B3%7D-%60frac%7B3%60cdot3%7D%7B%60frac%7B3%7D%7B3%7D%7D(%60frac%7B%60frac%7B%60frac%7B3%7D%7B3%7D%7D%7B3%7D%7D%7B3%7D%2B3-3%60frac%7B3%7D%7B3%7D)%7D))
