### ISSUE TITLE
V3.0 update: the top-level function ExprASTResult will have a panic error when a runtime error occurs

### ISSUE THREAD

**Issue by dengsgo** [dengsgo/math-engine#4]
V3.0 update: the top-level function `ExprASTResult` will have a panic error when a runtime error occurs
.

Most of the time you should use `ParseAndExec`, which automatically handles the errors that occur with  `ExprASTResult` .  Use recover to catch the panic if you really need to call  `ExprASTResult` :

```go
defer func() {
	if e := recover(); e != nil {
		// todo
	}
}()
ExprASTResult(expr)
```

**Comment by aiddroid** [comment]
你好，博文的相关参考资料能补充一下吗？相信会对读者很有帮助

**Comment by dengsgo** [comment]
> 你好，博文的相关参考资料能补充一下吗？相信会对读者很有帮助

具体一些，你想要的补充关于哪方面的参考资料？

**Comment by aiddroid** [comment]
> > 你好，博文的相关参考资料能补充一下吗？相信会对读者很有帮助
> 
> 具体一些，你想要的补充关于哪方面的参考资料？

比如二叉树具体是怎么构建的写的似乎不太详细，还有文章里提到的lhs op rhs （left hand side operator right hand side ）这些缩写应该是有出处的， 如果相关的参考链接能够都附在文章最后，就更清晰了。

例如表达式二叉树，我还看了这篇文章 https://zhuanlan.zhihu.com/p/54670963

**Comment by dengsgo** [comment]
> 比如二叉树具体是怎么构建的写的似乎不太详细

二叉树构建基于一个操作符优先级算法 Operator-precedence parser ，链接 [wikipedia](https://en.wikipedia.org/wiki/Operator-precedence_parser)，这个链接在博文中有提到的。这个算法的原则是将高优先的二元操作递归成二叉树较深的节点以便于后续深度扫描计算结果时使用（为什么要用深度扫描？）。详细的说明未在文中展开说，我还是更希望读者能够基于wiki 和 代码自行体会。

> 还有文章里提到的lhs op rhs （left hand side operator right hand side ）这些缩写能够备注一下， 

LHS, OP, RHS 分别是 Left-hand side、Operator、Right-hand side 的缩写，这个应该是在二元计算中常用的缩写了，可能非计算机专业理解上有点困难，我在后续文章改进中会补上说明。

> 或者您参考过的觉得有价值的链接能够都附在文章最后，就更清晰了。

其实很多的知识点都是零碎的，我参考和实现的理论大多都是编译原理的基础知识。你可能需要类似你说的那种把这些都介绍一遍的科普文，我没找过这方面的文章，可能帮不到你。如果你对这方面感兴趣，推荐阅读《数据结构与算法C语言版》和《编译系统透视》。
