### ISSUE TITLE
自定义函数不能注销

### ISSUE THREAD

**Issue by scgywx** [dengsgo/math-engine#7]
1、自定义函数只能注册，不能注销
2、自定义函数可不可以加一个绑定自定义参数(不是把参数写在公式里)，因为自定义函数有些可能需要传一些对象，按目前的设计，要么把对像做成全局变量，要么就是用unsafe pointer，

**Comment by dengsgo** [comment]
> 1、自定义函数只能注册，不能注销

是的，不允许卸载自定义的函数。因为注册函数之后，默认后面可以在任何地方调用而不用担心 panic。

> 2、自定义函数可不可以加一个绑定自定义参数(不是把参数写在公式里)，因为自定义函数有些可能需要传一些对象，按目前的设计，要么把对像做成全局变量，要么就是用unsafe pointer，

有没有具体的样例代码，可以详细的说一下使用场景。

**Comment by scgywx** [comment]
我做一个游戏战斗，里面用到公式，但是公式是策划写的，公式里面会用到双方的属性值，但是每场战斗的双方对像不是同一个，在取属性的时候就没办法获取对像。
假设公式是样写的：  PA_ATK() * 1.2 - PB_DEF() //意思是攻击方的攻击 * 1.2 - 被击方的防御。
这里没有对像绑定，只能用全局变量。

**Comment by dengsgo** [comment]
> 我做一个游戏战斗，里面用到公式，但是公式是策划写的，公式里面会用到双方的属性值，但是每场战斗的双方对像不是同一个，在取属性的时候就没办法获取对像。
> 假设公式是样写的： PA_ATK() * 1.2 - PB_DEF() //意思是攻击方的攻击 * 1.2 - 被击方的防御。
> 这里没有对像绑定，只能用全局变量。

取属性是指调用 PA_ATK() 这个自定义函数吗？

**Comment by scgywx** [comment]
对，自定义函数。我现在想到个解决方案就是，ATK(1)，DEF(2)，，这里的1表示攻击方，2表示被击方，这样获取同一个属性，只需要修改参数值就行了。。但还是少不了一个全局map来保存这个数字对应的Player对像。

**Comment by dengsgo** [comment]
> 对，自定义函数。我现在想到个解决方案就是，ATK(1)，DEF(2)，，这里的1表示攻击方，2表示被击方，这样获取同一个属性，只需要修改参数值就行了。。但还是少不了一个全局map来保存这个数字对应的Player对像。

这个需求超出了 `math-engine` 的实现范畴，如果你有什么好的实现想法，欢迎探讨 -)
