### ISSUE TITLE
Proposal: Please start using Semantic Versioning

### ISSUE THREAD

**Issue by KateGo520** [dengsgo/math-engine#8]
I found that this project already [supports Go modules](https://github.com/dengsgo/math-engine/blob/master/go.mod). But sadly, the [tags](https://github.com https://github.com/dengsgo/math-engine/tags) doesn't follow [Semantic Versioning](https://semver.org), which means that all tags of this project will be ignored by Go modules and replaced by pseudo-versions, go get acts weirdly when tags are not in that form. It would be great to have the tagged release be named in the format vX.X.X format so that go mod can read it. 
```
	github.com/dengsgo/math-engine v0.0.0-20200627074419-8918d8f8ea02
```
Else the mod file shows something like `github.com/dengsgo/math-engine v0.0.0-20200627074419-8918d8f8ea02` which is not very readable and difficult to upgrade. It’s hard to verify which version is in use. This is not conducive to version control.

So, I propose this project to follow Semantic Versioning in future versions. For example, `v1.0.1`, `v2.0.0`, `v3.1.0-alpha`, `v3.1.0-beta.2`etc, so that other project can use tag in go.mod.

**Comment by KateGo520** [comment]
@dengsgo  Could you help me review this issue? Thx :p

**Comment by dengsgo** [comment]
v3.1.0 has been pushed.  I'll close the issue until it happens again.

**Comment by KateGo520** [comment]
@dengsgo  Thank you for your contribution!
